import Head from 'next/head'
import { Button } from '@mui/material'

export default function Home() {
  return (
    <>
      <Head>
        <title>Tailwindcss and MUI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex flex-row p-5 space-x-3'>
        <p className='text-3xl font-bold underline'>Hello World!</p>
        <Button className='text-xl m-5 font-bold' variant="contained">Contained</Button>
      </div>
    </>
  )
}
